/**
 * Created by Administrator on 2014/8/20.
 */
define(function(require){
    require('zepto');
    $(document).on({
        'ajaxStop':function(){
            setTimeout(function(){
                $('#load-animate').hide();
            },200);
        },
        'ajaxStart':function(){
            $('#load-animate').show();
        }
    });
    require.async('js/canvasGame.js',function(){
        $('#load-animate').hide();
        setTimeout(function(){
            $('#canvas').canvasGame({
                target:'#canvas',
                img:'/images/5-1206010S421-50.jpg',
                percent:0.5,
                loadTarget:'#ajax-load',
                loadLocation:'/mobileLoad.html'
            });
        },20);

    });
});
